name: "ROS"
description: "My content for the Why ROS? section of the new www.ros.org"

baseurl: "http://osrf.github.io/www.ros.org"

paginate: 10

# markdown: rdiscount
markdown: kramdown
permalink: pretty
pygments: true
